### ISSUE TITLE
Optimize Project Structure

### ISSUE THREAD

**Issue by wusatosi** [Visualizd/client#6]
Currently, our src folder is structured by property like this:
```
- components
	- Dashboard-component.vue
	- Panel-something.vue
	- Panel-other-thing.vue
	- Some-random-other-compoent.vue
- utils
	- Util-for-panel.ts
	- Util-for-dashboard.ts
	- Request-API-SDK.ts
- views
	- Panel.vue
	- Login.vue
	- Home.vue
	- Random.vue
```
but I predict that as our frontend project grow bigger, this project structure will lead to crowded scenario like this:
```
- components
	- [33 files for different pages/ functionality] 
- utils
	- [20 files for different pages/ functionality]
- views
	- [25 files for different pages/ functionality]
```
Basically, too much files in one folder.

I propose we structure our directory structure by functionality:
```
- Panels
	- Panel-something.vue
	- Panel-other-thing.vue
	- Util-for-panel.ts
	- Panels.vue
- dashboard
	- Dashboard-component.vue
	- Dashboard.vue
- login
	- Login.vue
- random-other-compoent
	- Some-random-other-compoent.vue
	- Util-for-dashboard.ts
	- Random.vue
- shared
	- Request-API-SDK.ts
```
Which will end up with more folders but cleaner structure, and I think it will encourage componentization.

This is meant to be open for discussion.

**Comment by williamjallen** [comment]
Something to consider closely as we begin work with Svelte.  I'll close this since it doesn't relate to Svelte directly.
